### PR TITLE
Fix route registration

### PR DESCRIPTION
**Pull request by gurgentil**
- Replace `hasWebRoute` with `$this->loadRoutesFrom`
- Move livewire components to the `Http/...` namespace
- Create a basic test for the form page (currently failing)

### CODE REVIEW

**Comment by drewroberts** [comment]
@gurgentil Take a look at this:

- https://laravel-livewire.com/docs/2.x/package-dev

**Comment by gurgentil** [comment]
@drewroberts I tried registering the component with `Livewire::component` but that didn't fix it either.

**Comment by gurgentil** [comment]
@drewroberts the issue was related to the order the service providers were registered in `TestCase`.

**Review by drewroberts — APPROVED** [review]
Thank you! 🎩

**Pull request merged**
