### PR TITLE
Remove duplicated view registration

### PR DESCRIPTION
**Pull request by gurgentil**

### CODE REVIEW

**Comment by drewroberts** [comment]
@gurgentil Can you resolve the Psalm error?

**Comment by gurgentil** [comment]
@drewroberts the psalm error is happening because we have a computed property called `activeStep` and the method that computes it is named `getActiveStepProperty`. I can take a further look at it tomorrow

**Comment by drewroberts** [comment]
I want to add back the changes I'm trying to do with that test case branch:

https://github.com/roberts/leads/pull/26

**Review by drewroberts — APPROVED** [review]
Thank you! 🏀

**Pull request merged**
